### ISSUE TITLE
[BUG] NullReferenceException

### ISSUE THREAD

**Issue by KiwiHawk** [ShadowTheAge/yafc#101]
I was checking YAFC's Sea Block compatibility when I got this error. I'm guessing it's not mod specific.

Object reference not set to an instance of an object.

   at YAFC.MainScreen.FadeDrawer.CreateDownscaledImage() in C:\projects\YAFC\YAFC\Windows\MainScreen.cs:line 562
   at YAFC.MainScreen.<ShowPseudoScreen>b__56_0(Object x) in C:\projects\YAFC\YAFC\Windows\MainScreen.cs:line 447
   at YAFC.UI.Ui.ProcessAsyncCallbackQueue() in C:\projects\YAFC\YAFCui\Core\Ui.cs:line 223

YAFC 0.5.5

Steps:

1. Open YAFC
2. Click Create new project
3. Click Done on milestones screen
4. Click Menu, Return to starting screen
5. Click Don't save
6. Click Create new project
7. NullReferenceException appears over Milestones screen

![image](https://user-images.githubusercontent.com/59639/110081469-da1eb280-7df0-11eb-8488-d7fbb8d83220.png)

**Comment by ShadowTheAge** [comment]
I guess that is related to this https://github.com/ShadowTheAge/yafc/issues/94

**Comment by KiwiHawk** [comment]
Let me know if you need more info to reproduce it

**Comment by ShadowTheAge** [comment]
Fixed for the next version (0.5.7)
