### ISSUE TITLE
[BUG] IndexOutOfRangeException when setting some fuel sources

### ISSUE THREAD

**Issue by DaleStan** [ShadowTheAge/yafc#124]
In YAFC 0.5.7.1, when planning the production of the Space Exploration item "Interstellar Travel Data", there is a warning saying "Fuel not specified. Solution is inaccurate." This is perfectly reasonable, but when I click on the fuel slot, I get an IndexOutOfRangeException.

I've attached the YAFC file and a save you can use to synchronize the mods:
[Test.yafc](https://github.com/ShadowTheAge/yafc/files/6760451/Test.yafc.zip)
[SE.zip](https://github.com/ShadowTheAge/yafc/files/6760450/SE.zip)

The error I get is:

```
Index was outside the bounds of the array.

   at YAFC.ProductionTableView.<>c__DisplayClass11_0.<OpenProductDropdown>g__DropDownContent|7(ImGui gui) in C:\projects\YAFC\YAFC\Workspace\ProductionTable\ProductionTableView.cs:line 135
   at YAFC.UI.ImGui.DoGui(ImGuiAction action) in C:\projects\YAFC\YAFCui\ImGui\ImGuiBuilding.cs:line 182
   at YAFC.UI.ImGui.BuildGui(Single width) in C:\projects\YAFC\YAFCui\ImGui\ImGuiBuilding.cs:line 203
   at YAFC.UI.AttachedPanel.Build(ImGui gui) in C:\projects\YAFC\YAFCui\ImGui\DropDownPanel.cs:line 55
   at YAFC.UI.Window.Build(ImGui gui) in C:\projects\YAFC\YAFCui\Core\Window.cs:line 226
   at YAFC.UI.ImGui.DoGui(ImGuiAction action) in C:\projects\YAFC\YAFCui\ImGui\ImGuiBuilding.cs:line 182
   at YAFC.UI.ImGui.BuildGui(Single width) in C:\projects\YAFC\YAFCui\ImGui\ImGuiBuilding.cs:line 203
   at YAFC.UI.Window.Render() in C:\projects\YAFC\YAFCui\Core\Window.cs:line 84
   at YAFC.UI.Ui.Render() in C:\projects\YAFC\YAFCui\Core\Ui.cs:line 182
```

If I click the X in the corner of that window, instead of clicking the Close button, I get:
```
Index was outside the bounds of the array.

   at YAFC.ProductionTableView.<>c__DisplayClass11_0.<OpenProductDropdown>g__DropDownContent|7(ImGui gui) in C:\projects\YAFC\YAFC\Workspace\ProductionTable\ProductionTableView.cs:line 135
   at YAFC.UI.ImGui.DoGui(ImGuiAction action) in C:\projects\YAFC\YAFCui\ImGui\ImGuiBuilding.cs:line 182
   at YAFC.UI.ImGui.BuildGui(Single width) in C:\projects\YAFC\YAFCui\ImGui\ImGuiBuilding.cs:line 203
   at YAFC.UI.ImGui.CalculateState(Single width, Single pixelsPerUnit) in C:\projects\YAFC\YAFCui\ImGui\ImGui.cs:line 143
   at YAFC.UI.ImGui.DrawPanel(Rect rect, IPanel panel) in C:\projects\YAFC\YAFCui\ImGui\ImGuiBuilding.cs:line 66
   at YAFC.UI.AttachedPanel.Build(ImGui gui) in C:\projects\YAFC\YAFCui\ImGui\DropDownPanel.cs:line 55
   at YAFC.UI.Window.Build(ImGui gui) in C:\projects\YAFC\YAFCui\Core\Window.cs:line 226
   at YAFC.UI.ImGui.DoGui(ImGuiAction action) in C:\projects\YAFC\YAFCui\ImGui\ImGuiBuilding.cs:line 182
   at YAFC.UI.ImGui.BuildGui(Single width) in C:\projects\YAFC\YAFCui\ImGui\ImGuiBuilding.cs:line 203
   at YAFC.UI.Window.Render() in C:\projects\YAFC\YAFCui\Core\Window.cs:line 84
   at YAFC.UI.Ui.Render() in C:\projects\YAFC\YAFCui\Core\Ui.cs:line 182
```

**Comment by ShadowTheAge** [comment]
I have fixed the error but yafc thinks that entity doesn't have any fuels, even hidden "technical" ones that doesn't seem correct

**Comment by ShadowTheAge** [comment]
v0.5.8 with the fix has been published here https://github.com/ShadowTheAge/yafc/releases
Feel free to reopen the issue if needed
