### ISSUE TITLE
[BUG] Unable to run YAFC.dll in linux

### ISSUE THREAD

**Issue by SlipperyPotatoes** [ShadowTheAge/yafc#127]
Version: YAFC beta v0.5.7.1 (latest)
I am going to preface this with that I am still new to linux and this is all being done using the Crostini linux container for chromeos which is based on debian.

The issue is on running its unable to run the shared library 'SDL2-2.0.so.0' _or one of its dependencies_. I have verified the library is indeed installed under the directory /usr/lib/i386-linux-gnu after using the 3 provided commands for installing SDL. 

The full output in the terminal is below:

Unhandled exception. System.DllNotFoundException: Unable to load shared library 'SDL2-2.0.so.0' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at YAFC.YafcLib.DllResolver(String libraryname, Assembly assembly, Nullable`1 searchpath) in C:\projects\YAFC\YAFC\YafcLib.cs:line 65
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at YAFC.UI.Ui.Start() in C:\projects\YAFC\YAFCui\Core\Ui.cs:line 36
   at YAFC.Program.Main(String[] args) in C:\projects\YAFC\YAFC\Program.cs:line 12
Aborted (core dumped)

**Comment by ShadowTheAge** [comment]
Unfortuantely I'm not a linux user so my advices may help but may not be the cause of the problem or the correct way to fix things:
dotnet searches the common places for the libraries it need but I don't know the exact algorithm or paths it uses.

To start try putting these libraries "closer" where it should be able to locate it, for example in the yafc directory
Also check the access rights for the libraries, and the user you are launching yafc from
If you are starting yafc from console, try to start it from the directory where it is located (although it shouldn't matter, but just to have the most simple possible environment)

Or you can setup the LD_DEBUG environment variable (`export LD_DEBUG=all`) - with that you will get all the paths where dotnet searches for the library

**Comment by veger** [comment]
I suppose YAFC is build for 64-bit (Linux and you are running a 32-bit OS (suggested by `i386-linux-gnu`)
